name: Robot Framework Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt


      - name: Run E2E tests (with console log)
        run: |
          robot --loglevel TRACE --outputdir . --console verbose e2etests/test_e2e.robot

      - name: Run API tests (with console log)
        run: |
          robot --loglevel TRACE --outputdir . --console verbose apiTests/test_api.robot

      - name: Upload Robot Framework reports
        uses: actions/upload-artifact@v4
        with:
          name: robot-reports
          path: |
            log.html
            report.html
            output.xml
